# Generated by Django 5.1.2 on 2024-10-31 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('alcohol_consumption', models.CharField(choices=[('None', 'None'), ('Rarely', 'Rarely'), ('Weekly', 'Weekly'), ('Daily', 'Daily')], max_length=20)),
                ('physical_activity_level', models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active')], max_length=20)),
                ('smoking_status', models.CharField(choices=[('Non-Smoker', 'Non-Smoker'), ('Former Smoker', 'Former Smoker'), ('Current Smoker', 'Current Smoker')], max_length=20)),
                ('diet_type', models.CharField(choices=[('Omnivore', 'Omnivore'), ('Vegetarian', 'Vegetarian'), ('Vegan', 'Vegan'), ('Pescatarian', 'Pescatarian')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Data',
                'verbose_name_plural': 'User Data',
                'db_table': 'tb_user_info',
            },
        ),
        migrations.CreateModel(
            name='UserScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_risk_score', models.FloatField()),
                ('diabetes_risk_score', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_scored', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='chatbot.userdata')),
            ],
            options={
                'verbose_name': 'Scoring',
                'verbose_name_plural': 'Scorings',
                'db_table': 'tb_last_user_scoring',
            },
        ),
    ]
